# Site settings
title: Uber Uno
description: "Rules and other stuff on the uno game that is played at APS during lunch hour."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Build settings
markdown: kramdown
permalink: pretty
